name = "mei-tra-cloudflare"
main = "src/index.ts"
compatibility_date = "2026-02-13"
workers_dev = true

[[durable_objects.bindings]]
name = "GAME_ROOM"
class_name = "RoomDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomDurableObject"]
